'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _20_astuces_pour_personnaliser_votre_relation_client() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20-astuces-pour-personnaliser-votre-relation-client", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _610311ab0aefbc4da1f79026_Header_Blog_equiperfactuHEADER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("610311ab0aefbc4da1f79026_Header-Blog-equiperfactuHEADER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bersgf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bersgf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capturefn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capturefn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cdh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cdh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cyber_security_protection_of_the_internet_computer_system_is_a_concept_hackers_use_digital_technology_free_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cyber-security-protection-of-the-internet-computer-system-is-a-concept-hackers-us"& _ 
                        "e-digital-technology-free-photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disk04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property facture_impayee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facture-impayee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property facture_impayee1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facture-impayee1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property facture_impayee2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facture-impayee2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fgtr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fgtr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Find_Saved_Passwords_833x474() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Find-Saved-Passwords-833x474", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property geedf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("geedf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gfd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gfd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gfdhjgffg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gfdhjgffg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ghffgfin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghffgfin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hgesctfr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hgesctfr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hgghghg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hgghghg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khhh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khhh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_financial_accounting_business_management_accountan_accounting_5ac0bb0eec7084_7926291615225802389685() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-financial-accounting-business-management-accountan-accounting-5ac0bb0eec7"& _ 
                        "084.7926291615225802389685", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_inventory_management_software_warehouse_management_inventory_management_5b43314a691e95_8181917015311301864306() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-inventory-management-software-warehouse-management-inventory-management-5"& _ 
                        "b43314a691e95.8181917015311301864306", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kjhhhj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjhhhj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kjhhhj1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjhhhj1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kjhhhj2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjhhhj2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kjj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log_4_1024x484() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log-4-1024x484", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logiciel_de_facturation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logiciel-de-facturation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lonn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lonn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lotrf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lotrf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mcd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mcd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mld() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mld", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_customer_service_icon_png_image_2731437() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-customer-service-icon-png-image_2731437", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recherche_de_fournisseurs_potentiels_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recherche-de-fournisseurs-potentiels-03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property relation_826x459() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relation-826x459", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property relation_acheteur_fournisseur_coeur_dernieres_Rencontres_Decision_Achats_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relation-acheteur-fournisseur-coeur-dernieres-Rencontres-Decision-Achats-F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shopping_list_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping-list-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property téléchargement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("téléchargement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tttt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tttt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property visuel_gc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("visuel-gc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property visuel_gc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("visuel-gc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ygu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ygu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zertt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zertt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
